### ISSUE TITLE
wrong results when using str_extents with some symbols

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/gdtools#15]
```
str_extents("∀")

     [,1] [,2]
[1,]    0    0
```

**Comment by hadley** [comment]
Might need to ensure that it's encoded in UTF-8 before passing on to Cairo.

**Comment by davidgohel** [comment]
I am not sure but I think it's because this symbol is not in the available character of the font. when using font `symbol`, I get:

    > str_metrics("∀", fontname = "symbol")
       width   ascent  descent 
    8.554688 8.630859 0.000000

**Comment by hadley** [comment]
Oh that's another good point. But we should definitely convert to UTF8 for people on Windows.

**Comment by davidgohel** [comment]
Right, I forget to reuse `Rf_translateCharUTF8` in `str_metrics`.

**Comment by jeroenooms** [comment]
It's often easier to use `enc2utf8` in your R wrapper than doing the conversion in C++.

**Comment by davidgohel** [comment]
I believe so.
But in our case, the package is written to be used from other packages on the C level (to make easier R graphical device implementation).

**Comment by hadley** [comment]
It would also be useful to have a fallback - maybe if the symbol isn't available use `M`?

**Comment by davidgohel** [comment]
yes

I will try this week.

**Comment by hadley** [comment]
Any chance you'll have time to do it next week? It would really help with ggplot2 development

**Comment by davidgohel** [comment]
I have just published a branch (loadfont). 

This is not the final version - I am actually trying to identify a weird issue. This issue doesn't seems to occur when used in the devices (devSVG.cpp for example) but it can be reproduced with `str_metrics_ext`.

```
library(dplyr)
library(stringr)
library(purrr)

# read fonts from system... ----
fontlist <- sys_fonts() %>% 
  as.tbl() %>% 
  mutate(file = as.character(file), family = as.character(family) ) %>% 
  filter( str_detect(file, pattern = "\\.ttf$"), 
          weight == 80, slant == 0 )

# read fonts from system... ----

xx_ext <- map_df(fontlist$file, .f = function(f) {
  out <- as.list(str_metrics_ext("Hello World", fontsize = 12, fontfile = f ) )
  out$file <- f
  out
} )
xx_sys <- map_df(fontlist$family, .f = function(f) {
  out <- as.list(str_metrics("Hello World", fontsize = 12, fontname = f ) )
  out$file <- f
  out
} )



```
