### ISSUE TITLE
str_extents() and str_metrics() restrict font size to be integer

### ISSUE THREAD

**Issue by yixuan** [davidgohel/gdtools#17]
Hi, thanks for the amazing package. I was not aware of this project before I wrote my own [fontr](https://github.com/yixuan/fontr) package, which essentially tried to do similar things as what you have here.

I noticed that in the file `font_metrics.cpp`, both functions mentioned in the subject line declare the `fontsize` argument to be integer. However, in reality font size (in point size) has no such restriction, and actually `CairoContext::setFont` in file `CairoContext.cpp` has font size in double, so I believe it is trivial to allow double-typed arguments in these two functinos.

**Comment by davidgohel** [comment]
Hi,

Thanks for pointing that. 
I think you're right, `fontsize` should be a double and not an integer...

**Comment by yixuan** [comment]
Another issue is that currently `CairoContext` uses an image surface as backend, which means that all the font metrics are in device units (hence pixels), and they are all integers. To allow font metrics to be double, it seems to be better to use a PDF surface.

**Comment by davidgohel** [comment]
Do we need something else than pixel unit when developing R graphical devices?

**Comment by yixuan** [comment]
For vector graphics such as SVG and PDF. :-)

**Comment by davidgohel** [comment]
OK, I used to compute font metrics in pixel units and it worked fine so far...

Can you make sure your PR does not affect https://github.com/mdecorde/RSvgDevice/?

David

**Comment by yixuan** [comment]
Hi David,
I've tested the building process and it is all OK.
I also tried to compare the generated SVG using `gdtools` with and without the PR.

```r
library(RSvgDevice)

set.seed(123)
alphabet = c(letters, LETTERS)
strs = sapply(1:10, function(x) paste(sample(alphabet, 10), collapse = ""))

devSVG("test2.svg")
plot(1, type = "n", xlim = c(0, 1), ylim = c(0, 1))
text(runif(10), runif(10), strs)
dev.off()
```

Before applying the PR, part of the SVG file looks like
```svg
<text x='397.79' y='105.04' font-size='12.00' font-family='Arial'>oOuRTcyYVt</text>
<text x='240.27' y='365.43' font-size='12.00' font-family='Arial'>XxHCeQlboP</text>
<text x='326.75' y='464.20' font-size='12.00' font-family='Arial'>UJGWFHzAmg</text>
<text x='603.81' y='99.93' font-size='12.00' font-family='Arial'>YUIMbwXjnS</text>
<text x='331.91' y='193.21' font-size='12.00' font-family='Arial'>hvusZgkXlK</text>
<text x='565.86' y='430.70' font-size='12.00' font-family='Arial'>cwNfAjWHXq</text>
<text x='584.93' y='264.56' font-size='12.00' font-family='Arial'>IetnNvLKZs</text>
<text x='401.90' y='97.32' font-size='12.00' font-family='Arial'>NGJawkrBpe</text>
<text x='283.74' y='249.69' font-size='12.00' font-family='Arial'>mIuMeXTONh</text>
<text x='135.80' y='323.01' font-size='12.00' font-family='Arial'>gHrGpiJeuv</text>
```

After applying the PR, this part becomes
```svg
<text x='397.78' y='104.98' font-size='12.00' font-family='Arial'>oOuRTcyYVt</text>
<text x='241.09' y='365.65' font-size='12.00' font-family='Arial'>XxHCeQlboP</text>
<text x='326.75' y='464.14' font-size='12.00' font-family='Arial'>UJGWFHzAmg</text>
<text x='604.47' y='100.04' font-size='12.00' font-family='Arial'>YUIMbwXjnS</text>
<text x='332.40' y='193.32' font-size='12.00' font-family='Arial'>hvusZgkXlK</text>
<text x='566.36' y='430.81' font-size='12.00' font-family='Arial'>cwNfAjWHXq</text>
<text x='585.09' y='264.62' font-size='12.00' font-family='Arial'>IetnNvLKZs</text>
<text x='402.56' y='97.43' font-size='12.00' font-family='Arial'>NGJawkrBpe</text>
<text x='283.90' y='249.98' font-size='12.00' font-family='Arial'>mIuMeXTONh</text>
<text x='136.62' y='323.12' font-size='12.00' font-family='Arial'>gHrGpiJeuv</text>
```

As you can see, the difference is almost imperceptible.
