### ISSUE TITLE
function 'gdtools_RcppExport_validate' not provided by package 'gdtools'

### ISSUE THREAD

**Issue by jeroenooms** [davidgohel/gdtools#25]
Starting to see [this error](https://cran.r-project.org/web/checks/check_results_rvg.html) on some platforms. Maybe related to the Rcpp 0.12.3 upgrade? @hadley @eddelbuettel @jjallaire

**Comment by jeroenooms** [comment]
Looks like this problem has resolved itself once everything has been rebuilt against the latest Rcpp.

**Comment by eddelbuettel** [comment]
For the record, what platform(s) was that on?

**Comment by jeroenooms** [comment]
I noticed it on both windows and osx.

**Comment by eddelbuettel** [comment]
Right. Uwe always rebuilds everything on Windows anyway, not sure about OS X. It is is basically recommended that way,

**Comment by MGES** [comment]
这个问题又出现了。这是要等到Rcpp更新吗？

**Comment by MGES** [comment]
This problem has occurred again. Is this to wait until the Rcpp update?

**Comment by jeroen** [comment]
You need to rebuild packages that link to gdtools, for example `rvg` and `rsvg`.

**Comment by MGES** [comment]
Thank you very much!
