### ISSUE TITLE
License not present

### ISSUE THREAD

**Issue by wwood** [davidgohel/gdtools#28]
Hi,

I'm attempting to package gdtools for GNU Guix and I noticed that while the README says 

>The gdtools package is licensed under the GPLv3. 

Thanks for making it free. However, there is not any license included in the source. Also, do you mean GPL3 or "GPL3 or later" ?

Thanks,
ben

**Comment by davidgohel** [comment]
Hi

The licence is available on the cran page of gdtools 

https://cran.r-project.org/package=gdtools

I am not an expert with license, does that cause you an issue to package it?

**Comment by hadley** [comment]
Technically you should include a copy of the GPLv3 license, see e.g. https://github.com/hadley/readr

**Comment by davidgohel** [comment]
ok, thanks
