### ISSUE TITLE
Font metrics differ across platforms

### ISSUE THREAD

**Issue by lionel-** [davidgohel/gdtools#30]
In a Debian:testing docker:

``` r
gdtools::str_metrics("disp")
##    width   ascent  descent 
## 24.82031  9.12500  2.50000 
```

And on OSX:

``` r
gdtools::str_metrics("disp")
##     width    ascent   descent 
## 22.013672  8.636719  2.501953 
```

cf hadley/svglite#69
cc @hadley

**Comment by davidgohel** [comment]
When I test with the same fonts on both system, I get the same results:

I first had to install on my OSX font *DejaVu* because it is the only available font within system fonts on my Debian docker (from `https://hub.docker.com/r/rocker/rstudio/`). The font versions are not the same (but font specifications should be almost identical).

```
# from OSX
> gdtools::str_metrics("disp", fontname = "DejaVu Sans")
    width    ascent   descent 
24.820312  9.117188  2.496094 
```

```
# from docker
> gdtools::str_metrics("disp", fontname = "DejaVu Sans")
   width   ascent  descent 
24.82031  9.12500  2.50000 
```

`gdtools::str_metrics` is using the best matching fontname, not the exact name.

**Comment by lionel-** [comment]
Would it be possible to provide fonts instead of relying on system fonts?

So we could call svglite with something like:

```r
fonts <- c(sans = "path/font.ttf", serif = "other/font.ttf")
svglite(fonts = fonts)
```

**Comment by hadley** [comment]
I think that would need some tooling in `gdtools` so that we could register a font to a specified path. 

@lionel- could you explore open source fonts that we could embed in vdiffr? Ideally they'd be small, and have a permissive license so we could distribute.

**Comment by lionel-** [comment]
Bitstream or Liberation would be a good fit.

**Comment by hadley** [comment]
Bitstream Vera seems like a good fit.  I wonder if it's worth making a package just to contain those fonts (and to provide a single helper function that let you install them locally)

**Comment by davidgohel** [comment]
I don't know yet how much work it involves but it should be possible

**Comment by davidgohel** [comment]
I made successful tests!

@hadley I plan to do it Friday. There will be a new class `CairoExtContext` (close to `CairoContext`) and the method `context_create` will have two init parameters: a file for *regular* font and a file for *symbol* font (for the fallback). The method `setFont` would not need `fontfile` parameter (and files will only be loaded once which should improve performances).

**Comment by hadley** [comment]
Sounds great!

Do you think it's worth including Bitstream Vera in this package, or should we create a new one?

**Comment by davidgohel** [comment]
We will need Bitstream Vera, at least for running tests. It seems reasonable to have another package for containing a list of open source fonts. Also, ttf format will probably not be enough, we will also need the woof and the svg version of fonts (browsers are not always compatible with *True Type Font*).

**Comment by hadley** [comment]
I don't really care about generating svgs with correctly embedded fonts (as anything that literally embeds links to local files will break when you publish), just making sure we can reliably generate svgs that are identical regardless of the platform.

@lionel- do you want to take a first pass at the package?

**Comment by lionel-** [comment]
Sure, I'll find some time tomorrow.

**Comment by hadley** [comment]
BTW font package is at http://github.com/lionel-/fontquiver

**Comment by davidgohel** [comment]
The new branch `fontfile_context` can be tested.

https://github.com/davidgohel/gdtools/blob/fontfile_context/src/gdtools.cpp#L29

`FontFileContext`constructor requires 4 string arguments that should specify font files (regular, bold, italic, bold-italic). Method `fontfile_context_set_font` has a new argument `fallback`, it should be a single `character`. A warning occurs if a character cannot be map in the font table reference.

**Comment by lionel-** [comment]
Great! I'll soon fix some issues in fontquiver and add a second font (otherwise it's quite an empty quiver) so I can release to cran.

**Comment by lionel-** [comment]
fontquiver is now on CRAN.

**Comment by hadley** [comment]
🎉🎉🎉🎉🎉🎉
