### ISSUE TITLE
ggsave stops working and references error in gdtools

### ISSUE THREAD

**Issue by Alesja** [davidgohel/gdtools#37]
Hi David, 
I am running command ggsave ("plot1. svg") in R 3.2.3 and gdtools 0.1.4 and get the following error message: 

Saving 3.68 x 3.69 in image 
Terminate called after throwing an instance of 'Rcpp::function_not_exported' what(): function not exported: C++ function with signature 'bool(*context_set_font)(XPtrCairoContext,std::string,double,bool,bool)' not found in gdtools This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.

Thanks for looking into that,
Aleksandra

**Comment by davidgohel** [comment]
Hi

Can you provide `sessionInfo()` and a reproducible example?

Thanks
David
