### ISSUE TITLE
Compilation error on install for R v3.4

### ISSUE THREAD

**Issue by chrisalcantara** [davidgohel/gdtools#38]
This is connected to an issue I'm having with downloading `svglite`, which requires gdtools. 

I receive this issue when I try to download gdtools:

![screen shot 2017-06-17 at 5 53 15 pm](https://user-images.githubusercontent.com/5307200/27256527-df2042ba-5385-11e7-8e4e-1d31f864dc61.png)

I'm using R v3.4. Perhaps its something to do with my version of `cairo`?

**Comment by davidgohel** [comment]
I think that could be the reason. 

Could you try the following instructions?

(From https://groups.google.com/forum/#!topic/reporters-package/9WP5uqP2hr8)

1. Install homebrew. Follow internet instructions.
2. From terminal type: "brew install cairo"
3. In R type: install.packages("gdtools")
