### ISSUE TITLE
gdtools does not install on FreeBSD

### ISSUE THREAD

**Issue by jgjl** [davidgohel/gdtools#42]
Hi, 

gdtools does not install on FreeBSD, because the configure script expects bash to be in /bin.
On FreeBSD, if bash is installed, it is located in /usr/local/bin/bash. If I link bash to /bin/bash
the installation works fine.

The easiest fix would be to use sh in the configure script instead of bash, I guess?

Best,

Jeremias

**Comment by davidgohel** [comment]
@jeroen just noticed your work on that, thanks!
