### ISSUE TITLE
Yet another Cairo issue (MacOS)

### ISSUE THREAD

**Issue by slyrus** [davidgohel/gdtools#43]
When I try to install gdtools via:

install.packages("gdtools")

I get:

```
trying URL 'https://cran.rstudio.com/src/contrib/gdtools_0.1.7.tar.gz'
Content type 'application/x-gzip' length 35268 bytes (34 KB)
==================================================
downloaded 34 KB

* installing *source* package ‘gdtools’ ...
** package ‘gdtools’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-L/usr/local/Cellar/cairo/1.14.12/lib -lcairo
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because cairo was not found. Try installing:
 * deb: libcairo2-dev (Debian, Ubuntu)
 * rpm: cairo-devel (Fedora, CentOS, RHEL)
 * csw: libcairo_dev (Solaris)
 * brew: cairo (OSX)
If cairo is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a cairo.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```

If I do things "by-hand" and do:

R CMD INSTALL gdtools_0.1.7.tar.gz

then things work fine.

So... it would be easy to chalk this up to some sort of PKG_CONFIG_PATH problem, yet I'm troubled by the facts that PKG_LIBS are successfully found, but not PKG_CFLAGS. It's a bit hard to debug the chain of emacs/R/install.packages, but somewhere along the line, at least on MacOS, we're losing/not finding PKG_CFLAGS.

**Comment by davidgohel** [comment]
Can you try the following:

Close all R sessions (not mandatory but from experience, it's the best solution).
In a terminal, run the following command:

```
brew install cairo
```

Open an R session and run the following code:

`install.packages("gdtools", type = "source")`

**Comment by davidgohel** [comment]
And if you cairo is already installed...

----
For mac users. This is sometimes happening with mac os X updates.

Close all R sessions (not mandatory but from experience, it's the best solution).
In a terminal, run the following commands:

```
brew update
brew upgrade
brew reinstall cairo
```

Open an R session and run the following code:

`install.packages("gdtools", type = "source")`
