### ISSUE TITLE
I'm still seeing issue 43

### ISSUE THREAD

**Issue by slyrus** [davidgohel/gdtools#46]
Yet another Cairo issue (MacOS) issue #43 is still giving me trouble and none of the workarounds fix things. This is on mojave.

**Comment by davidgohel** [comment]
Can you show the logs and also confirm you are not in this case: https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

**Comment by davidgohel** [comment]
Each time there is an mac os update, this issue is coming back... 

Sorry to insist if I am wrong :) Did you follow what is explained here: https://github.com/davidgohel/gdtools/issues/43#issuecomment-375056815

**Comment by slyrus** [comment]
Yes, I have followed those instructions multiple times with no luck. BUT I did manage to get things to install. I have to go a command line and do R CMD INSTALL ... Trying to do it with install.package something goes haywire and the CFLAGS are lost. ISTR having done this once before but forgot what the workaround was.

**Comment by davidgohel** [comment]
> Trying to do it with install.package something goes haywire and the CFLAGS are lost.

What are you talking about, specifically gdtools or all packages?? 

What mean ISTR? 

There is no CFLAGS to position in the command here https://github.com/davidgohel/gdtools/issues/43#issuecomment-375056815). 

... I will have a look when I will update to mojave.

**Comment by swvanderlaan** [comment]
I also have this issue ...

**Comment by davidgohel** [comment]
Did you just update to mojave?

**Comment by jeroen** [comment]
Why are you installing from source? Please don't use anaconda.

**Comment by swvanderlaan** [comment]
So, I did the following:

```
R CMD INSTALL Downloads/gdtools_0.1.7.tar.gz
* installing to library ‘/usr/local/lib/R/3.5/site-library’
* installing *source* package ‘gdtools’ ...
** package ‘gdtools’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-L/usr/local/Cellar/cairo/1.16.0/lib -lcairo
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because cairo was not found. Try installing:
 * deb: libcairo2-dev (Debian, Ubuntu)
 * rpm: cairo-devel (Fedora, CentOS, RHEL)
 * csw: libcairo_dev (Solaris)
 * brew: cairo (OSX)
If cairo is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a cairo.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘gdtools’
* removing ‘/usr/local/lib/R/3.5/site-library/gdtools’

swvanderlaan@Sanders-MacBook ~
$ pkg-config --cflags cairo
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found

swvanderlaan@Sanders-MacBook ~
$ brew install libffi
Warning: libffi 3.2.1 is already installed and up-to-date
To reinstall 3.2.1, run `brew reinstall libffi`

swvanderlaan@Sanders-MacBook ~
$ brew reinstall libffi
==> Reinstalling libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.2.1.mojave.bottle.
Already downloaded: /Users/swvanderlaan/Library/Caches/Homebrew/downloads/89b4ef328be250153e7a2b39982ac446e0b3bbfe7f3e2708912ba1976862c302--libffi-3.2.1.mojave.bottle.tar.gz
==> Pouring libffi-3.2.1.mojave.bottle.tar.gz
==> Caveats
libffi is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/usr/local/opt/libffi/lib"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/libffi/3.2.1: 16 files, 296.8KB

swvanderlaan@Sanders-MacBook ~
$ pkg-config --cflags cairo
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
```

Which didn't solve it. Then I put in my `bash`-profile:

```
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig"
```

Now it was solved when running:

```
R CMD INSTALL Downloads/gdtools_0.1.7.tar.gz

```

So after downloading the pre-compiled MacOS version of `gdtools`.

Solved. But it's not ideal. Hope this helps in debugging ...

**Comment by jeroen** [comment]
Why don't you use `install.packages("gdtools")` in R?

**Comment by swvanderlaan** [comment]
I did as well: same result. Either way I try it, it doesn't work. See below the output when running `install.packages("gdtools").

```
* installing *source* package ‘gdtools’ ...
** package ‘gdtools’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-L/usr/local/Cellar/cairo/1.16.0/lib -lcairo
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because cairo was not found. Try installing:
 * deb: libcairo2-dev (Debian, Ubuntu)
 * rpm: cairo-devel (Fedora, CentOS, RHEL)
 * csw: libcairo_dev (Solaris)
 * brew: cairo (OSX)
If cairo is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a cairo.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘gdtools’
* removing ‘/usr/local/lib/R/3.5/site-library/gdtools’
```

And here is my `brew config` output:

```
HOMEBREW_VERSION: 2.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f07fe5c5cdfdf0f424bba7b879faa38aedc8ee4
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 07d6a7b951c6992fd8cae3f917510ef81aefef33
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.1jkVuIO8bN/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/swvanderlaan/Library/Logs/Homebrew
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
CLT headers: 10.1.0.0.1.1539992718
XQuartz: 2.7.11 => /opt/X11
```

It appears I have XQuartz and Xcode and CLT properly set. If I run `brew info cairo` I get this:

```
cairo: stable 1.16.0 (bottled), HEAD
Vector graphics library with cross-device output support
https://cairographics.org/
/usr/local/Cellar/cairo/1.16.0 (117 files, 5.5MB) *
  Poured from bottle on 2019-03-12 at 10:36:28
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cairo.rb
==> Dependencies
Build: pkg-config ✔
Required: fontconfig ✔, freetype ✔, glib ✔, libpng ✔, pixman ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 83,081 (30 days), 202,883 (90 days), 583,774 (365 days)
install_on_request: 5,671 (30 days), 16,812 (90 days), 66,295 (365 days)
build_error: 0 (30 days)
```

I've logged out and logged in again, but the issue remains: I can't install `gdtools` - or other packages dependent on `cairo`. 

I do wonder: how do I check `PKG_CONFIG_PATH`? That will probably get me closer to the answer.

**Comment by swvanderlaan** [comment]
> Did you just update to mojave?

Yep. Clean install - wish I hadn't done that ...

**Comment by swvanderlaan** [comment]
> Why are you installing from source? Please make sure you use the latest and official [R for MacOS from CRAN](https://cran.r-project.org/bin/macosx/)

I tried installing R via CRAN - which I don't like, I want everything via `brew`, for other reasons than this.
I tried installing R via `brew`. 

Either way: installing `gdtools` via a pre-compile *.tgz-file, 'source', or just as is from CRAN using `install.packages()` all amount to the same error. But I wonder what happens if I follow the instructions/hints given:

```
If cairo is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a cairo.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'

```

I just don't know _how_ to discover whether `PKG_CONFIG_PATH` includes `cairo.pc` and if not, how to fix that, and if it does, what to do next.

**Comment by swvanderlaan** [comment]
Ok. I think I found the solution. 

As I wrote before, I want to use `brew` to install as much as possible. In principle `brew` doesn't change `r` at its core, but it doesn't necessarily install `r` via source. 

So here's what I did to get a 'Science MacOS-R-brew environment', it's over-complete, but well, maybe also partly interconnected. And since I'm not a programmer I don't have the overview of what could be relevant and what is not, so I just report everything I did.

- clean install of MacOS Mojave 10.14.3
- installation of CommandLineTools via `xcode-select --install`
- install some perl packages: `sudo cpan YAML Getopt::Long Statistics::Distributions`
- install `brew` as per brew.sh
- install some other packages via brew that I just need for other reasons, but for completeness I note them here:

```
brew install coreutils gnu-sed wget rename git pkg-config cairo freetype gd libharu git imagemagick lzo hdf5 bison samtools bcftools vcftools libxml2 gdal libgit2 openblas libsvg curl geos boost mariadb-connector-c findutils zlib boost gsl

brew tap caskroom/cask && brew install cask

brew cask install xquartz && brew cask install java

brew install python llvm

pip3 install argparse numpy scipy scikit-learn pandas openpyxl xlrd jupyter
```
- install `r` via brew from source:

```
brew reinstall r --build-from-source --verbose --display-times
```
Obviously the latter two arguments aren't needed, I was just curious.

- install `RStudio`: `brew cask install rstudio`.

- when I ran the issue of rights, for some reason some packages/installations change that I simply type: `sudo chown -Rv $(whoami) /usr/local/Cellar/*`.


These posts gave me some hints:
- https://stackoverflow.com/questions/14009606/homebrew-r-build-missing-cairo
- https://stackoverflow.com/questions/45548133/unable-to-install-gdtools-or-svglite/55118863#55118863
- https://stackoverflow.com/questions/16826069/osx-10-7-5-fatal-error-ft2build-h-file-not-found
- https://stackoverflow.com/questions/20457290/installing-r-with-homebrew

**Comment by jeroen** [comment]
You are really overcomplicating things. I want to emphasize that everything will work out of the box if you use the official R for MacOS from CRAN.

For future reference, if users really want to install from source, to debug this problem you can run this on the command line:

```
pkg-config --cflags cairo
```

And that will likely show the issue. In my case (mojave) it shows:

```
pkg-config --cflags cairo
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
```

So I did this:

```r
export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
```

And then start R, and then it works.
