### ISSUE TITLE
Can we use the Cairo font api?

### ISSUE THREAD

**Issue by jeroen** [davidgohel/gdtools#47]
Currently the package uses a mix of cairo and fontconfig apis. However fontconfig is a bit of a pain on Windows/Mac.

Cairo also provides [high level font api](https://www.cairographics.org/manual/cairo-cairo-scaled-font-t.html#cairo_scaled_font_extents) which builds on the appropriate platform specific font-backend. On Windows it can use the native windows font apis instead of fontconfig.

The `gdtools` package would be more robust if it would only use font metrics via the cairo api and not include fontconfig directly. Would this be possible, or are there features in gdtools that really need fontconfig?

**Comment by davidgohel** [comment]
I think the first versions were not relying on fontconfig (but it is a long time I did not work on this and I need time to refresh my memory...). Also if I remember correctly, @lionel- needed fontconfig to be able to manage extra fonts with `svglite` and `vdiffr`. 

Lionel, any thoughts on that?

**Comment by lionel-** [comment]
I think Jeroen is right that we should use the Cairo abstraction for selecting fonts, if possible. The problem is that the abstraction might be a toy or rudimentary abstraction. How does it work? Can you pass fontconfig-like patterns to select a font? Can you pass font files containing multiple fonts and select the right one based on a pattern?

**Comment by jeroen** [comment]
I'm not super familiar with the font management, but R itself doesn't call font-config directly in the cairo devices, and neither do most libraries that rely on cairo for rendering (e.g. imagemagick). So probably graphical devices that use `gdtools` should be able to use the same mechanics?

**Comment by davidgohel** [comment]
yes I do agree. fontconfig was only used by `font_family_exists` at first and Cairo is having the same kind of function without fontconfig dep. 

> Can you pass fontconfig-like patterns to select a font? Can you pass font files containing multiple fonts and select the right one based on a pattern?

If all of that is possible (Cairo package) this will require time!

**Comment by davidgohel** [comment]
fontconfig is not used anymore (replaced by systemfonts)
