### ISSUE TITLE
installation on windows failed

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/gdtools#5]

**Comment by hadley** [comment]
Are you tied to the current use of autoconf? We might be able to simplify to just an simple `configure` script.

**Comment by davidgohel** [comment]
Yes

I should do what you've done on package xml2 with libxml2.

**Comment by hadley** [comment]
Let me know if you need some help - I don't know anything, but I can get @jeroenooms to take a look.

**Comment by davidgohel** [comment]
Same for me. 

In short, I have adapted the configure from Cairo package (but something is wrong with the Windows part). What's done on xml2 looks  simpler. 

If @jeroenooms can't help or has no time for that I will try to do it friday.

**Comment by jeroenooms** [comment]
Sure I'll have a look

**Comment by davidgohel** [comment]
thanks

**Comment by jeroenooms** [comment]
The windows build is fixed @ https://github.com/davidgohel/gdtools/pull/7. I'll have a look at the unix autoconf stuff later.

**Comment by jeroenooms** [comment]
Are you shipping headers in `./inst` on purpose? I.e. do you intend other packages will link to your C++ functions? Otherwise we should just move those into `./src`.

**Comment by hadley** [comment]
Yes, the headers are there deliberately - but I'm writing that interface at the moment.
