### ISSUE TITLE
fontconfig changes R locale

### ISSUE THREAD

**Issue by AshesITR** [davidgohel/gdtools#51]
Due to [this commit](https://github.com/behdad/fontconfig/commit/2938e4d72da40f6bb0d22086c519a9852a820f40), fontconfig calls do `setlocale`.
This propagates back to R and causes https://github.com/davidgohel/flextable/issues/125 .

MCVE (start in a fresh R session):

``` r
Sys.getlocale()
#> [1] "LC_COLLATE=German_Germany.1252;LC_CTYPE=German_Germany.1252;LC_MONETARY=German_Germany.1252;LC_NUMERIC=C;LC_TIME=German_Germany.1252"
fonts <- gdtools::sys_fonts()
Sys.getlocale()
#> [1] "German_Germany.1252"
```

<sup>Created on 2019-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

A possible remedy would be saving and restoring the locale on every call at the R level, akin to `withr::with_locale()`.

**Comment by AshesITR** [comment]
I confirmed the following functions change my locale when run in a fresh instance.

```r
gdtools::sys_fonts()
gdtools::set_dummy_conf()
gdtools::str_metrics(x = "asdf")
gdtools::glyphs_match(x = "asdf")
gdtools::match_font(font = "sans")
gdtools::font_family_exists(font_family = "sans")
gdtools::str_extents(x = "asdf")
gdtools::match_family(font = "sans")
gdtools::m_str_extents(x = "asdf")
```

Apparently subsequent calls (after some initialisation happened?) do not change the locale.

@davidgohel Are you working on this issue? If not, I could give it a try?

**Comment by davidgohel** [comment]
Hello,

No I am not working on it - you can help of course, this will be welcome! 

Just to let you know, I'd like to get rid of fontconfig - I will work on that later this year.

**Comment by thomasp85** [comment]
of potential interest... I'm currently working on a similar effort in https://github.com/thomasp85/systemfonts

**Comment by davidgohel** [comment]
@thomasp85 thanks for the information!

**Comment by AshesITR** [comment]
@davidgohel I checked out the FC_LANG branch and did a clean install.
Unfortunately, the issue reappeared :(
