### ISSUE TITLE
unable to update

### ISSUE THREAD

**Issue by MAJH79** [davidgohel/gdtools#54]
devtools::install_github('davidgohel/gdtools')
Downloading GitHub repo davidgohel/gdtools@master
✔  checking for file ‘/private/var/folders/lt/jl4vpwwx2_db205fbb8ysls00000gp/T/RtmpIEK12D/remoteseb53472623f8/davidgohel-gdtools-99f13ba/DESCRIPTION’ ...
─  preparing ‘gdtools’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘gdtools_0.2.0.tar.gz’
   
* installing *source* package ‘gdtools’ ...
** using staged installation
Using PKG_CFLAGS=-I/usr/local/opt/cairo/include/cairo
Using PKG_LIBS=-L/usr/local/opt/cairo/lib -lcairo -lfreetype
** libs
rm -f gdtools.so CairoContext.o RcppExports.o font_metrics.o gdtools.o raster_to_base64.o versions.o
clang++ -arch x86_64 -ftemplate-depth-256 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/opt/cairo/include/cairo -I../inst/include/ -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined -Wno-unknown-pragmas -c CairoContext.cpp -o CairoContext.o
In file included from CairoContext.cpp:7:
/usr/local/opt/cairo/include/cairo/cairo-ft.h:46:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [CairoContext.o] Error 1
ERROR: compilation failed for package ‘gdtools’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools’
Error: Failed to install 'gdtools' from GitHub:
  (converted from warning) installation of package ‘/var/folders/lt/jl4vpwwx2_db205fbb8ysls00000gp/T//RtmpIEK12D/fileeb5339b9e57e/gdtools_0.2.0.tar.gz’ had non-zero exit status

**Comment by davidgohel** [comment]
Can you wait for CRAN binary to be ready?

Otherwise make sure freetype2 is installed. 

```
brew install freetype2
```

**Comment by davidgohel** [comment]
Does you "thumb up" means it solved the issue?
