### ISSUE TITLE
No 0.2.0 NEWS

### ISSUE THREAD

**Issue by QuLogic** [davidgohel/gdtools#56]
The NEWS file does not contain any news for 0.2.0. There are also no tags in this repository, so I can't even run a quick&easy compare.

**Comment by davidgohel** [comment]
Thanks, I added an entry in NEWS file.

Sorry, I have no idea what *quick&easy compare* refers to.

If you have an issue with `gdtools`, please add a reproducible example (and the result of `sessionInfo()`)

**Comment by QuLogic** [comment]
If your repo has tags, I can go to, e.g., https://github.com/davidgohel/gdtools/compare/0.1.9..0.2.0 and see what changed easily (without having to find old tarballs on CRAN and compare them.)

**Comment by davidgohel** [comment]
ok, I will try to manage tags. 
Use the following to compare with previous version:

https://github.com/davidgohel/gdtools/compare/6674760..8a94fa3

**Comment by QuLogic** [comment]
Thanks!
