### ISSUE TITLE
Fix build for R 4.0 on MacOS

### ISSUE THREAD

**Issue by jeroen** [davidgohel/gdtools#59]
Simon Urbanek says:

gdtools breaks in the current R alpha build, because it's using pkg-config --libs for cairo but don't fall back to --static if there is no shared version available and thus not all necessary libraries are included (see below). Unfortuantely, gdtools configure doesn't follow any standard R package rules, so there is no way for me to fix that by setting PKG_LIBS as gdtools configure blows those away. Please make sure you honor PKG_* flags as a primary source in your configure (ideally in all packages) and if possible use --libs --static in cases where shared build is not available.

If you want to test yourself all binaries for R 4.x are in
https://mac.r-project.org/libs-4/

**Comment by davidgohel** [comment]
Is there a package or a documentation that I can use as a reference to understand what needs to be done?

Did he provide a date (time is clearly an issue for me at the moment)?

**Comment by jeroen** [comment]
Don't worry, I'll fix it.

**Comment by davidgohel** [comment]
Oh, thank you!

**Comment by jeroen** [comment]
I think it should be fixed now.
