### ISSUE TITLE
Release for libcairo 1.18

### ISSUE THREAD

**Issue by jeroen** [davidgohel/gdtools#64]
Hi @davidgohel 

I [updated the windows libraries to libcairo 1.18](https://github.com/davidgohel/gdtools/commit/28cefbc0ca181ce9c34e411f2d712039d273fed0), which also includes support for the new ARM64 hardware. Can you submit a release to cran with these fixes?

**Comment by davidgohel** [comment]
Hi, ok thanks

Sure, I will - probably next week.

**Comment by jeroen** [comment]
Thank you!

**Comment by davidgohel** [comment]
Hi, "package gdtools_0.3.4.tar.gz is on its way to CRAN."

**Comment by jeroen** [comment]
Thanks!
