### ISSUE TITLE
Installation error: object ‘match_fonts’ was not exported by ‘namespace:systemfonts’

### ISSUE THREAD

**Issue by jaum20** [davidgohel/gdtools#69]
I am using Linux Minx 21.3,  5.15.0-89-generic and R 4.4.1.

`install.packages("gdtools")`

> error: object ‘match_fonts’ was not exported by ‘namespace:systemfonts’

Also, `r-cran-systemfonts `is installed

**Comment by davidgohel** [comment]
Install latest systemfonts
