### ISSUE TITLE
Install wants to download cairio from github, how to do an offline install

### ISSUE THREAD

**Issue by kdalenberg** [davidgohel/gdtools#72]
I need to install the gdtools r package in a system that does not have outbound internet access due to security constraints.  

How can I do an offline install of gdtools including the version of cairo the installer tries to grab from github?

**Comment by davidgohel** [comment]
I can only recommend you to copy the tar.xz that fit your needs based on https://github.com/davidgohel/gdtools/blob/master/tools/winlibs.R and then to adapt https://github.com/davidgohel/gdtools/blob/master/tools/winlibs.R so that it `file.copy()` instead of `download.file()`

**Comment by kdalenberg** [comment]
The path if(!file.exists("../windows/cairo/include/cairo/cairo.h")){

Is that relative to where the gdtools tar file is that I've downloaded and copied to the system?  Or is that relative to somewhere else?

**Comment by kdalenberg** [comment]
Can you provide a syntax example of file.copy()?
